# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
# Remap prefix from 'Ctrl-b' to 'Ctrl-space'
unbind C-b
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix
# Split window using \ and -
# Using \ because it's easier to reach than |
bind '\' split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Enable mouse mode
set -g mouse on
# 256 colors terminal
set-option -sa terminal-overrides ",xterm*:Tc"
# Window index starts at 1
set -g base-index 1
setw -g pane-base-index 1

# Remember windows 
set -g renumber-windows on
# Plugins configuration
set -g @colors-solarized '256'

# Vim keybindings

set-window-option -g mode-keys vi

# tmux-yank
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# tmux-contiuum
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
set -g @continuum-save-uptime 'on'
# tmux-resurrect
set -g @resurrect-strategy-nvim 'session'
# Reload config file
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded."
# This has to be the last row
run '~/.tmux/plugins/tpm/tpm'
