local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
vim.keymap.set("n", "<leader>gf", builtin.git_files, {})
vim.keymap.set("n", "<C-s>", builtin.live_grep, {})
vim.keymap.set("n", "<leader><leader>", builtin.buffers, {})
require("telescope").load_extension("projects")
vim.api.nvim_set_keymap("n", "<leader>p", ":Telescope projects<CR>", { noremap = true })
