alias cat=bat
alias rcat='\cat'
alias lg=lazygit
alias ldo=lazydocker
alias ls='eza $eza_params'
alias l='eza --git-ignore $eza_params'
alias ll='eza --all --header --long $eza_params'
alias llm='eza --all --header --long --sort=modified $eza_params'
alias la='eza -lbhHigUmuSa'
alias lx='eza -lbhHigUmuSa@'
alias lt='eza --tree $eza_params'
alias tree='eza --tree $eza_params'
alias cd="z"
alias p="python3"
alias d="docker"
alias dc="docker compose"
alias c="clear"
alias v="nvim"
alias vim="nvim"
